// Core library exports
export const MOVIE_API_BASE_URL = 'https://www.omdbapi.com/'

export * from './types'
export * from './omdb'
export * from './compute-omdb'
export * from './constants'
export * from './utils'
export * from './search-utils'
export * from './upcoming'
export * from './aggregate-artists'
export * from './order-shows'
export * from './is-dev'
export * from './ai-types'
export * from './ai-discovery'
export * from './movie-assistant'
export * from './recommendations'
export * from './logger'
export * from './use-movies'
