/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ImdbIdRouteImport } from './routes/$imdbId'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoWorkosRouteImport } from './routes/demo/workos'

const ImdbIdRoute = ImdbIdRouteImport.update({
  id: '/$imdbId',
  path: '/$imdbId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoWorkosRoute = DemoWorkosRouteImport.update({
  id: '/demo/workos',
  path: '/demo/workos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$imdbId': typeof ImdbIdRoute
  '/demo/workos': typeof DemoWorkosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$imdbId': typeof ImdbIdRoute
  '/demo/workos': typeof DemoWorkosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$imdbId': typeof ImdbIdRoute
  '/demo/workos': typeof DemoWorkosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$imdbId' | '/demo/workos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$imdbId' | '/demo/workos'
  id: '__root__' | '/' | '/$imdbId' | '/demo/workos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImdbIdRoute: typeof ImdbIdRoute
  DemoWorkosRoute: typeof DemoWorkosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$imdbId': {
      id: '/$imdbId'
      path: '/$imdbId'
      fullPath: '/$imdbId'
      preLoaderRoute: typeof ImdbIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/workos': {
      id: '/demo/workos'
      path: '/demo/workos'
      fullPath: '/demo/workos'
      preLoaderRoute: typeof DemoWorkosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImdbIdRoute: ImdbIdRoute,
  DemoWorkosRoute: DemoWorkosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
